### ISSUE TITLE
It is possible to select multiple values?

### ISSUE THREAD

**Issue by SamSundar1** [RiftValleySoftware/RVS_AutofillTextField#1]

**Comment by ChrisMarshallNY** [comment]
Thanks for the interest! Sorry for not getting back to you sooner. Not sure why I'm not getting notifications for issues.

I have not designed it to do that. Frankly, not sure why we would want to do it.

The whole idea is “fast n’ furious.” We start typing, the list appears, and refines as we type. At some point, we decode to choose one of the items in the menu. We do that, the control immediately fills the text box, and the menu disappears.

That said, it’s a standard UITableView, so it can be configured to allow multiple selection. It’s just that I would need to figure out a UI scheme to allow that.

The class is open, and can be subclassed, so it could be possible to add that functionality.
